#!/usr/bin/python
# Copyright (c) 2013, Gao Wang <gaow@bcm.edu>
# GNU General Public License (http://www.gnu.org/licenses/gpl.html)

from argparse import ArgumentParser, SUPPRESS
from SEQLinco.Utils import env, getColumn
from SEQLinco.Core import main

class Args:
    def __init__(self):
        self.parser = ArgumentParser(
        description = '''{}, encode sequence data for linkage analysis'''.format(env.proj),
        prog = env.prog,
        fromfile_prefix_chars = '@',
        epilog = '''Copyright (c) 2013 ~ 2014 Gao Wang <gaow@bcm.edu> and Di Zhang <di.zhang@bcm.edu> GNU General Public License''')
        self.parser.add_argument('--version',
                                 action='version',
                                 version='%(prog)s version {0}'.format(env.version))
        self.getEncoderArguments(self.parser)
        self.getLinkageArguments(self.parser)
        self.getIOArguments(self.parser)
        self.getRuntimeArguments(self.parser)
        self.parser.set_defaults(func=main)

    def get(self):
        return self.parser.parse_args()

    def getEncoderArguments(self, parser):
        vargs = parser.add_argument_group('Encoder arguments')
        vargs.add_argument('--size', default = 1, type = int,
                           help='''Number of variants to collapse into a bin. Set to 0 to collapse
        all variants into one bin. Default to 1 (1 variant per bin).''')
        vargs.add_argument('--blueprint', metavar = 'FILE',
                           help='''Blueprint file for super marker
        (format: "chr startpos endpos name distance").''')

    def getIOArguments(self, parser):
        vargs = parser.add_argument_group('Input / output options')
        vargs.add_argument('--tfam', metavar='FILE', required=True,
                           help='''Input pedigree and phenotype information in TFAM format.''')
        vargs.add_argument('--vcf', metavar='FILE', required=True, help='''Input VCF file, bgzipped.''')
        vargs.add_argument('--freq', metavar='FILE', help='''Info field name for allele frequency in VCF file.''')
        vargs.add_argument('--chrom-prefix', metavar='STRING', dest = 'chr_prefix',
                           help='''Prefix to chromosome name in VCF file if applicable, e.g., "chr".''')
        vargs.add_argument('-o', '--output', metavar='FILE', help='''Output file name prefix.''')
        vargs.add_argument('--format', metavar = 'FORMAT', nargs='*', default=['mlink'],
                           help='''Output format, choose from {} (multiple choices allowed).
        Default to MLINK format.'''.format(repr(env.formats.keys())))
        
    def getRuntimeArguments(self, parser):
        vargs = parser.add_argument_group('Runtime arguments')
        vargs.add_argument('-j', '--jobs', metavar='N', type = int, default = 2,
                           help='''Number of CPUs to use.''')
        vargs.add_argument('--vanilla', action='store_true',
                           help='''Encode data from scratch without loading cache.''')
        vargs.add_argument('--debug', action='store_true', help=SUPPRESS)

    def getLinkageArguments(self, parser):
        vargs = parser.add_argument_group('Linkage analysis options')
        vargs.add_argument('--runner', metavar='STRING', choices=['mlink', 'allegro', 'merlin'],
                           help='which subsequent linkage program do you want to run')
        vargs.add_argument('--moi', metavar='STRING', dest = "inherit_mode",
                           choices=['AD', 'AR', 'Xlinked', 'Y'],
                           help='Mode of inheritance, AD/AR: autosome dominant/recessive.')
        vargs.add_argument('--prevalence', metavar='FLOAT', type=float, default=.01,
                           help='Disease prevalence.')
        vargs.add_argument('--wild-pen', metavar='FLOAT', type=float, dest = "wild_pen",
                           help='Penetrance for wild type')
        vargs.add_argument('--muta-pen', metavar='FLOAT', type=float, dest = "muta_pen",
                           help='Penetrance for mutation')
        
if __name__ == '__main__':
    # check platform
    import platform
    system = platform.system()
    arch = platform.architecture()[0]
    if not ((system == 'Linux' and arch == '64bit') or system == 'Darwin'):
        env.error("{} cannot be executed on {}-{} computers "\
                  "(only 64bit Linux/Mac environment is supported)".format(env.prog, system, arch), exit = True)
    try:
        args = Args().get()
        args.func(args)
    except Exception as e:
        raise
        env.error("{}".format(e))
